// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseUrl = env("DIRECT_URL") || env("DATABASE_URL");

if (!databaseUrl) {
  throw new Error(
    "Database connection URL is missing in environment variables.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: databaseUrl,
  },
});
